export const AccountData = [
  
  {
    title: "Home 1",
    data: [
      {
        id: 1,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
      {
        id: 2,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
      {
        id: 3,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
      {
        id: 4,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
    ],
  },
  {
    title: "Home 2",
    data: [
      {
        id: 1,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
      {
        id: 2,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
      {
        id: 3,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
      {
        id: 4,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
    ],
  },
  {
    title: "Office 1",
    data: [
      {
        id: 1,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
      {
        id: 2,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
      {
        id: 3,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
      {
        id: 4,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
    ],
  },
  {
    title: "Compliment",
    data: [
      {
        id: 1,
        title: "electricity bill",
        amount: "15000",
        quantity:"40",
        distributed_to:"office 1",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
      {
        id: 2,
        title: "electricity bill",
        amount: "15000",
        quantity:"40",
        distributed_to:"office 1",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
      {
        id: 3,
        title: "electricity bill",
        amount: "15000",
        quantity:"40",
        distributed_to:"office 1",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
      {
        id: 4,
        title: "electricity bill",
        amount: "15000",
        quantity:"40",
        distributed_to:"office 1",
        description: "bill payed after date",
        COR: "PG_09y87nrg",
      },
    ],
  },
];
