export const ModalData = [{
  totalSummary:"2000000000",
  account_name:"Account 1",
  total_amount:"800000",
  amount_spent:"500000",
  amount_remaining:"300000",
  home1:[{
        id: 1,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR:"PG_09y87nrg",
      },
      {
        id: 2,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR:"PG_09y87nrg",
      },
      {
      id: 3,
      title: "electricity bill",
      amount: "15000",
      description: "bill payed after date",
      COR:"PG_09y87nrg",
      },
      {
        id: 4,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR:"PG_09y87nrg",
      },],
      home2:[{
        id: 1,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR:"PG_09y87nrg",
      },
      {
        id: 2,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR:"PG_09y87nrg",
      },
      {
      id: 3,
      title: "electricity bill",
      amount: "15000",
      description: "bill payed after date",
      COR:"PG_09y87nrg",
      },
      {
        id: 4,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR:"PG_09y87nrg",
      },],
      office1:[]
},
{
  account_name:"Account 2",
  total_amount:"600000",
  amount_spent:"500000",
  amount_remaining:"100000",
  home1:[{
        id: 1,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR:"PG_09y87nrg",
      },
      {
        id: 2,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR:"PG_09y87nrg",
      },
      {
      id: 3,
      title: "electricity bill",
      amount: "15000",
      description: "bill payed after date",
      COR:"PG_09y87nrg",
      },
      {
        id: 4,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR:"PG_09y87nrg",
      },],
      home2:[],

      office1:[{
        id: 1,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR:"PG_09y87nrg",
      },
      {
        id: 2,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR:"PG_09y87nrg",
      },
      {
      id: 3,
      title: "electricity bill",
      amount: "15000",
      description: "bill payed after date",
      COR:"PG_09y87nrg",
      },
      {
        id: 4,
        title: "electricity bill",
        amount: "15000",
        description: "bill payed after date",
        COR:"PG_09y87nrg",
      },],
},
    ];
