export const ModalData = [
  {
    id: "1",
    Name: "Rabia",
    Last_Name: "waheed",
    Email: "Rabia@gmail.com",
    Gender: [ "Female", "Male"],
    Contact: ["+92309874556"],
    Type: ["Employee", "Admin"],
  },
  {
    id: "2",
    Name: "Sana",
    Last_Name: "syed",
    Email: "Sana@gmail.com",
    Gender: ["Female", "Male"],
    Contact: ["+92309874556"],
    Type: ["Employee", "Admin"],
  },
  {
    id: "3",
    Name: "Atif",
    Last_Name: "riaz",
    Email: "atif@gmail.com",
    Gender: ["Male", "Female"],
    Contact: ["+92309874556"],
    Type: ["Employee", "Admin"],
  },
  {
    id: "4",
    Name: "Atif",
    Last_Name: "riaz",
    Email: "atif@gmail.com",
    Gender: ["Male", "Female"],
    Contact: ["+92309874556"],
    Type: ["Employee", "Admin"],
  },
];